In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [2]:
ds = load_breast_cancer()

In [3]:
train_set, test_set, train_labels, test_labels = train_test_split(
    ds.data[:, 0],  # features
    ds.target,  # labels
    test_size=0.25,  # split ratio
    random_state=1,  # set random seed
    stratify=ds.target)  # keep the same ratios 

In [11]:
print(train_set.shape)
X = train_set.reshape(-1, 1)
print(X.shape)

(426,)


(426, 1)

In [13]:
m = linear_model.LogisticRegression()
m.fit(X=X, y=train_labels)
new_test_set = test_set.reshape(-1, 1)
m.predict_proba(new_test_set)

array([[9.97355244e-01, 2.64475584e-03],
       [5.79904741e-01, 4.20095259e-01],
       [4.89418889e-01, 5.10581111e-01],
       [9.98081582e-01, 1.91841833e-03],
       [3.03482550e-02, 9.69651745e-01],
       [2.46328009e-02, 9.75367199e-01],
       [3.44560859e-01, 6.55439141e-01],
       [7.37983555e-03, 9.92620164e-01],
       [9.31323702e-01, 6.86762982e-02],
       [2.67420833e-01, 7.32579167e-01],
       [7.74629936e-02, 9.22537006e-01],
       [9.97698701e-01, 2.30129942e-03],
       [1.40364956e-01, 8.59635044e-01],
       [1.17525730e-01, 8.82474270e-01],
       [9.96393662e-01, 3.60633850e-03],
       [8.71767268e-02, 9.12823273e-01],
       [5.23677991e-02, 9.47632201e-01],
       [9.58226369e-01, 4.17736310e-02],
       [1.45622603e-01, 8.54377397e-01],
       [9.85914334e-01, 1.40856657e-02],
       [2.80216752e-01, 7.19783248e-01],
       [1.58397979e-02, 9.84160202e-01],
       [9.75394894e-01, 2.46051062e-02],
       [9.94702889e-01, 5.29711054e-03],
       [9.975722

In [21]:
m_predict = m.predict(new_test_set)
m.predict_proba([[20]])

array([[0.99679376, 0.00320624]])

In [15]:
from sklearn import metrics

metrics.confusion_matrix(test_labels, m_predict)

array([[45,  8],
       [ 7, 83]])

In [16]:
# calculate the accuracy
metrics.accuracy_score(test_labels, m_predict)

0.8951048951048951

In [17]:
# calculate the precision
metrics.precision_score(test_labels, m_predict)

0.9120879120879121

In [18]:
# calculate the recall
metrics.recall_score(test_labels, m_predict)

0.9222222222222223

In [19]:
# calculate the F1 score
metrics.f1_score(test_labels, m_predict)

0.9171270718232044