In [6]:
import numpy as np

In [12]:
np_arr1 = np.array([1, 2, 3, 4, 5])
np_arr2 = np.array([6, 7, 8, 9, 10])
np_sum = np_arr1 + np_arr2
np_sum

array([ 7,  9, 11, 13, 15])

In [15]:
arr_1d = np.array([1, 2, 3])
print(f"arr_1d: {arr_1d} \n dim: {arr_1d.ndim} shape: {arr_1d.shape} size: {arr_1d.size}")
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"arr_2d: {arr_2d} \n dim: {arr_2d.ndim} shape: {arr_2d.shape} size: {arr_2d.size}")
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(f"arr_3d: {arr_3d} \n dim: {arr_3d.ndim} shape: {arr_3d.shape} size: {arr_3d.size}")

arr_1d: [1 2 3] 
 dim: 1 shape: (3,) size: 3
arr_2d: [[1 2 3]
 [4 5 6]] 
 dim: 2 shape: (2, 3) size: 6
arr_3d: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 
 dim: 3 shape: (2, 2, 3) size: 12


In [17]:
arr1 = np.arange(0, 20)
arr2 = arr1.reshape(4, 5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
ones = np.ones((3, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
arr3 = np.array([1, 2, 3, 4, 5], dtype=np.float32)
arr3

array([1., 2., 3., 4., 5.], dtype=float32)