In [3]:
import numpy as np

In [6]:
row_students = np.array([1, 2, 3, 4])
row_math = np.array([65, 78, 90, 81])
row_english = np.array([71, 82, 79, 92])

students = np.array([row_students, row_math, row_english])
print(students.shape)
students

(3, 4)


array([[ 1,  2,  3,  4],
       [65, 78, 90, 81],
       [71, 82, 79, 92]])

In [8]:
students[1:, 3]

array([81, 92])

In [12]:
students[:, 1::2]

array([[ 2,  4],
       [78, 81],
       [82, 92]])

In [21]:
mask = (students >= 60) & (students <= 80)
print(mask)
np.where(mask, students, np.nan)

[[False False False False]
 [ True  True False False]
 [ True False  True False]]


array([[nan, nan, nan, nan],
       [65., 78., nan, nan],
       [71., nan, 79., nan]])

In [19]:
np.argwhere(mask)

array([[1, 0],
       [1, 1],
       [2, 0],
       [2, 2]])