In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1, 100, size=(5, 4))
arr

array([[15, 43, 89, 11],
       [98, 48, 95, 28],
       [12, 84, 40, 58],
       [60, 82, 64, 81],
       [28, 94, 87,  1]])

In [5]:
arr.sum()

1118

In [8]:
arr.max(axis=1)

array([89, 98, 84, 82, 94])

In [11]:
arr_3d = np.random.randint(1, 100, size=(3, 4, 5))
arr_3d

array([[[48, 69, 87, 16, 28],
        [74, 39, 75, 94, 14],
        [91, 32,  1, 62, 69],
        [34, 78, 40, 96, 27]],

       [[26, 77, 10, 12, 15],
        [ 5, 35, 13,  1, 65],
        [40, 68, 96, 48, 86],
        [99,  5, 37, 20, 90]],

       [[78, 80, 98, 19, 66],
        [89, 14, 61, 25, 52],
        [ 4, 98, 47, 14, 29],
        [74, 61, 40, 90,  8]]])

In [14]:
arr_3d.max(axis=2)

array([[87, 94, 91, 96],
       [77, 65, 96, 99],
       [98, 89, 98, 90]])