In [1]:
import numpy as np

In [2]:
arr = np.linspace(0, 5, 10)
arr

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [3]:
arr_view = arr.view()
arr2 = arr.copy()
arr_view

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [4]:
arr_view[0] = 100
arr

array([100.        ,   0.55555556,   1.11111111,   1.66666667,
         2.22222222,   2.77777778,   3.33333333,   3.88888889,
         4.44444444,   5.        ])

In [5]:
arr2

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])